ALTER TABLE envio ADD COLUMN IF NOT EXISTS municipio VARCHAR(45);
ALTER TABLE envio ADD COLUMN IF NOT EXISTS parroquia VARCHAR(45);
ALTER TABLE envio ADD COLUMN IF NOT EXISTS calle VARCHAR(45);
ALTER TABLE envio ADD COLUMN IF NOT EXISTS numero_guia VARCHAR(100);
ALTER TABLE envio ALTER COLUMN id_factura SET NOT NULL;
